name: Simple M3U Merger

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'

env:
  TZ: Asia/Shanghai

jobs:
  merge-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge files
      run: |
        # 下载源文件
        wget -q "https://raw.githubusercontent.com/mytv-android/BRTV-Live-M3U8/main/BRTV.m3u"
        wget -q "https://raw.githubusercontent.com/govan10/TV-list/main/%E5%A4%A9%E6%B4%A5%E8%81%94%E9%80%9A%E5%85%AC%E7%BD%91.m3u" -O tianjin.m3u

        # 合并文件（保留单个文件头）
        echo "#EXTM3U" > iptv.m3u
        tail -n +2 BRTV.m3u >> iptv.m3u  # 跳过第一个文件的头部
        tail -n +2 tianjin.m3u >> iptv.m3u  # 跳过第二个文件的头部

        # 清理临时文件
        rm -f BRTV.m3u tianjin.m3u

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add iptv.m3u
        if git diff-index --quiet HEAD --; then
          echo "没有内容变化"
        else
          git commit -m "自动合并: $(date +'%Y-%m-%d %H:%M')"
          git push origin HEAD:main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
