name: IPTV

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟运行一次（UTC时间）

jobs:
  merge-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # 必须设置才能推送更改

    - name: Merge M3U files
      run: |
        # 设置输出文件路径
        OUTPUT_FILE="$GITHUB_WORKSPACE/iptv.m3u"

        # 下载源文件
        curl -sSL "https://raw.githubusercontent.com/0047ol/BRTV-Live-M3U8/main/BRTV.m3u" -o brtv.m3u
        curl -sSL "https://raw.githubusercontent.com/govan10/TV-list/refs/heads/main/%E5%A4%A9%E6%B4%A5%E8%81%94%E9%80%9A%E5%85%AC%E7%BD%91.m3u" -o original.m3u

        # 处理北京台格式
        sed -E '
            s|#EXTINF:(-1)\s+tvg-name="([^"]+)",(.*)|#EXTINF:\1 tvg-id="\2" tvg-name="\2" tvg-logo="https://live.fanmingming.cn/tv/\2.png" group-title="北京",\3|
        ' brtv.m3u > processed_brtv.m3u

        # 合并文件（确保文件头唯一）
        {
            # 生成文件头
            echo "#EXTM3U"
            
            # 合并北京台内容（去重）
            awk '
            /^#EXTINF/ {
                key = $0
                sub(".*tvg-id=\"", "", key)
                sub("\".*", "", key)
                if (!seen[key]++) {
                    print $0
                    getline; print $0
                }
                next
            }
            { print }
            ' processed_brtv.m3u
            
            # 合并原始内容（排除北京分组）
            awk '
            /^#EXTM3U/ { next }
            /group-title="北京"/ { getline; next }
            { print }
            ' original.m3u
        } | sed '/^$/d' > "$OUTPUT_FILE"

        # 验证文件生成
        echo "=== 生成文件信息 ==="
        ls -l "$OUTPUT_FILE"
        echo "=== 前5行内容 ==="
        head -n 5 "$OUTPUT_FILE"

    - name: Commit and Push Changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git checkout --orphan latest_branch
        git add -A
        git commit -am "${GET_TIME}"
        git branch -D Files
        git branch -m Files

    - name: Push
      run: git push -f origin Files
