name: Auto Update IPTV

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'

env:
  TZ: Asia/Shanghai

jobs:
  merge-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # 必须设置为true才能保留凭证
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup environment
      run: echo "UPDATE_TIME=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_ENV

    - name: Process IPTV sources
      run: |
        # 源处理逻辑（保持与之前相同）
        wget -q https://raw.githubusercontent.com/0047ol/BRTV-Live-M3U8/main/BRTV.m3u -O brtv.m3u
        sed -n '/北京/,+1p' brtv.m3u > beijing.m3u
        sed -i '1i #EXTM3U' beijing.m3u
        sed -i -E 's|#EXTINF:(-1) tvg-name="([^"]+)",(.*)|#EXTINF:\1 tvg-id="\2" tvg-name="\2" tvg-logo="https://live.fanmingming.cn/tv/\2.png" group-title="北京",\3|' beijing.m3u

        wget -q https://raw.githubusercontent.com/govan10/TV-list/refs/heads/main/%E5%A4%A9%E6%B4%A5%E8%81%94%E9%80%9A%E5%85%AC%E7%BD%91.m3u -O original.m3u
        sed -i '/group-title="北京"/,+1d' original.m3u

        echo "#EXTM3U" > iptv.m3u
        cat beijing.m3u >> iptv.m3u
        cat original.m3u >> iptv.m3u
        
        awk '...' iptv.m3u > tmp.m3u  # 保持之前的去重逻辑
        sed -i '/^$/d' tmp.m3u
        mv tmp.m3u iptv.m3u
        echo "更新时间：${UPDATE_TIME}" > README.md

    - name: Commit changes
      run: |
        # 配置Git身份
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # 添加并提交更改
        git add .
        if git diff-index --quiet HEAD --; then
          echo "没有内容变化"
        else
          git commit -m "自动更新: ${UPDATE_TIME}"
          # 强制推送到当前分支
          git push origin HEAD:main
        fi
      env:
        # 使用GitHub提供的token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
